### ISSUE TITLE
go build fails

### ISSUE THREAD

**Issue by faide** [Noofbiz/SpaceCamp#1]
the current tip fails at building with an error saying the CursorSystem is not defined (and some others)
eg:

```bash
$ go build
# github.com/Noofbiz/SpaceCamp/systems
systems/accept.go:34:10: undefined: CursorSystem
systems/jobselect.go:56:2: undefined: CursorComponent
systems/jobselect.go:77:13: undefined: CursorSystem
systems/nameSelect.go:40:13: undefined: CursorSystem
systems/scene.go:35:2: undefined: CursorFace
systems/types.go:18:2: undefined: CursorComponent
```

maybe some files are missing from the dvcs repository ?

**Comment by Noofbiz** [comment]
Yeah sorry my laptop is dying so I had to push these changes to the remote to get them on my desktop even though it doesn't build yet! Apologies! Lol

**Comment by Noofbiz** [comment]
I am trying to figure out how to properly bundle the assets. Github doesn't like the large file sizes xD
